### ISSUE TITLE
[Circular import] issues when importing postqe after installation

### ISSUE THREAD

**Issue by yliu1240** [QEF/postqe#7]
Hi, all!
I've installed the postqe in a virtual environment and the installation process works well. However, I encountered an issue when trying to launch postqe in Python:

"""
>>> import postqe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../miniconda3/envs/qez2/lib/python3.9/site-packages/postqe/__init__.py", line 9, in <module>
    from . import pyqe
  File "/.../miniconda3/envs/qez2/lib/python3.9/site-packages/postqe/pyqe.py", line 2, in <module>
    from . import _pyqe
ImportError: cannot import name '_pyqe' from partially initialized module 'postqe' (most likely due to a circular import)
"""

Is there any other information I should provide to solve the issue?

Thanks in advance and have a nice day!

Best regards,

**Comment by pietrodelugas** [comment]
Hello 
Usually that error shows up when the compilation/linking of _pyqe.*.so fails. 
Please check if in the `lib//...//site-packages/postqe/` directory there is a `_pyqe.*.so` file. 
And please send the log of the installation with the stderr part included. 
Thanks and best regards
